# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 271)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit_api = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_api.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lineEdit_api.setObjectName("lineEdit_api")
        self.verticalLayout_2.addWidget(self.lineEdit_api)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit_token = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_token.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lineEdit_token.setObjectName("lineEdit_token")
        self.verticalLayout_2.addWidget(self.lineEdit_token)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.pushButton_ok = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_ok.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.verticalLayout_3.addWidget(self.pushButton_ok)
        self.verticalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UserLogin"))
        self.groupBox.setTitle(_translate("MainWindow", "Login"))
        self.label_2.setText(_translate("MainWindow", "API Endpoint"))
        self.label.setText(_translate("MainWindow", "Token"))
        self.pushButton_ok.setText(_translate("MainWindow", "Login"))
